name = Acrostia
description = A single column layout.
preview = preview.png

; Regions
regions[navigation]     = Navigation bar
; regions[header]         = Header
regions[content_top]    = Content top
regions[help]           = Help
regions[content]        = Content
regions[content_bottom] = Content bottom
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/acrostia/acrostia.css
